apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssl-exporter
  namespace: ops-monit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssl-exporter
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ssl-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ssl-exporter
subjects:
- kind: ServiceAccount
  name: ssl-exporter
  namespace: ops-monit
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ssl-exporter
  name: ssl-exporter
  namespace: ops-monit
spec:
  ports:
    - name: ssl-exporter
      protocol: TCP
      port: 9219
      targetPort: 9219
  selector:
    app: ssl-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-exporter
  namespace: ops-monit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-exporter
  template:
    metadata:
      name: ssl-exporter
      labels:
        app: ssl-exporter
    spec:
      containers:
        - name: ssl-exporter
          image: registry.cn-shenzhen.aliyuncs.com/starsl/ssl_exporter:0.1
          ports:
            - name: tcp
              containerPort: 9219
      serviceAccountName: ssl-exporter
      serviceAccount: ssl-exporter
